title: Th4ntis:~$
author:
  name: Th4ntis
  email: th4ntis.gox@simplelogin.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  A quick whoami and Cyber Security and Information Security blog by th4ntis.
# If you clone the Minima repo and build locally, use this setting.
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
# header_pages:
#  - blog.md
#  - notes.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: true

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: dark
  
  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"

  # Generate social links in footer.
  social_links:
    - { platform: github,         user_url: "https://github.com/th4ntis" }
    - { platform: twitter,        user_url: "https://twitter.com/th4ntis" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/damian-roneker" }
    - { platform: mastodon,       user_url: "https://infosec.exchange/@th4ntis" }
  # - { platform: HTB,            user_url: "https://app.hackthebox.com/profile/274909" }
  # - { platform: THM,            user_url: "https://tryhackme.com/p/th4ntis" }
  # - { platform: bluesky,        user_url: "https://bsky.app/profile/th4ntis.bsky.social" }
  # - { platform: x,              user_url: "https://x.com/th4ntis" }
  # - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }


